-- Enable the UUID generation function
create extension if not exists "uuid-ossp" with schema "extensions";

-- Create profiles table to store user data
create table "public"."profiles" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "email" text,
    "user_id" uuid,
    "full_name" text,
    "bio" text,
    "lifestyle" text,
    "sustainability_focus" text[],
    "climate_challenges" text[],
    "sustainability_knowledge" text,
    "next_task_due_at" timestamp with time zone,
    "total_eco_score" integer not null default 0,
    primary key ("id"),
    unique ("id"),
    foreign key ("user_id") references auth.users (id) on delete cascade
);

-- Set up Row Level Security
alter table "public"."profiles" enable row level security;
create policy "Users can view their own profiles." on "public"."profiles" for select using (auth.uid() = user_id);
create policy "Users can insert their own profile." on "public"."profiles" for insert with check (auth.uid() = user_id);
create policy "Users can update their own profile." on "public"."profiles" for update using (auth.uid() = user_id);

-- Create daily_tasks table to store tasks for each user
create table "public"."daily_tasks" (
    "id" bigint generated by default as identity,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "task_description" text,
    "is_completed" boolean not null default false,
    "assigned_date" date not null,
    "xp_value" integer,
    "eco_score" integer not null default 10,
    primary key ("id"),
    foreign key ("user_id") references auth.users (id) on delete cascade
);

-- Set up Row Level Security for daily_tasks
alter table "public"."daily_tasks" enable row level security;
create policy "Users can view their own tasks." on "public"."daily_tasks" for select using (auth.uid() = user_id);
create policy "Users can insert their own tasks." on "public"."daily_tasks" for insert with check (auth.uid() = user_id);
create policy "Users can update their own tasks." on "public"."daily_tasks" for update using (auth.uid() = user_id);
